repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff (lint, autofix)
        language: system
        entry: uv run ruff
        args: ["check", "--fix", "--exit-non-zero-on-fix", "."]        
        pass_filenames: false
        stages: [pre-commit]

      - id: black
        name: Black (format)
        language: system
        entry: uv run black
        args: ["."]
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: Pytest (quick)
        language: system
        entry: uv run pytest
        args: ["-q"]
        pass_filenames: false
        stages: [pre-commit]
