name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT for version-from-Git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies with uv
        run: |
          pip install uv
          uv sync --extra dev

      - name: Run pytest
        run: uv run pytest -q
