name: Release on main

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # required to push tags and create releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # must see tags & history

      - name: Bump tag from Conventional Commits (Angular)
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          tag_prefix: v
          create_annotated_tag: true
          # Choose ONE of the following:
          # default_bump: patch     # always bump at least patch if no hints
          # default_bump: false     # skip tagging if no feat/fix/BREAKING found

      - name: Create GitHub Release
        if: steps.tag.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag:  ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
